spring.application.name=ddblabs-timeparser-rules
spring.thymeleaf.cache=false

server.port=${TIMEPARSER_SERVER_PORT:8080}
server.servlet.context-path=${TIMEPARSER_URL_PREFIX:/app/timeparser-rules}
server.forward-headers-strategy=${TIMEPARSER_FORWARD_HEADERS_STRATEGY:framework}
spring.web.error.include-message=always
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,text/csv
server.compression.min-response-size=1024

debug=false
logging.level.root=${TIMEPARSER_LOG_LEVEL:INFO}
logging.level.org.springframework=${TIMEPARSER_SPRING_LOG_LEVEL:${TIMEPARSER_LOG_LEVEL:INFO}}

timeparser.database.path=${TIMEPARSER_DATABASE_PATH:timeparser-rules.sqlite}
timeparser.csv.rules-path=${TIMEPARSER_RULES_CSV_PATH:rules.csv}
timeparser.csv.tests-path=${TIMEPARSER_TESTS_CSV_PATH:tests.csv}
timeparser.security.username=${TIMEPARSER_SECURITY_USERNAME:admin}
timeparser.security.password=${TIMEPARSER_SECURITY_PASSWORD:admin}
